spring:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434/}
      chat:
        options:
          model: ${OLLAMA_CHAT_MODEL:deepseek-coder-v2:16b}
          temperature: ${OLLAMA_CHAT_TEMPERATURE:0.5}
  application:
    name: core

springdoc:
  swagger-ui:
    enabled: true                  # Enable Swagger UI
    deep-linking: true             # Enable deep linking
  api-docs:
    path: /api-docs                # Path to OpenAPI docs
logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){blue} %clr(${LOG_LEVEL_PATTERN: - %5p}) %clr(${PID:- }){magenta} %clr([%thread]){yellow}  %cyan(%logger{39}:%L)  %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    ru:
      ogbozoyan:
        cron:
          configuration:
            ControllerAdvice: OFF
