spring:
  application:
    name: cron-ai
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/cron_validator}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin}
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434/}
      embedding:
        options:
          model: nomic-embed-text
      chat:
        options:
          model: ${OLLAMA_CHAT_MODEL:mistral:latest}
          temperature: ${OLLAMA_CHAT_TEMPERATURE:0.5}
          functions:
            - "testFunction"
      vectorstore:
        pgvector:
          initialize-schema: true
          index-type: HNSW
          distance-type: COSINE_DISTANCE
          dimensions: 1536
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    enabled: true                  # Enable Swagger UI
    deep-linking: true             # Enable deep linking
  api-docs:
    path: /api-docs                # Path to OpenAPI docs
logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss.SSS}){blue} %clr(${LOG_LEVEL_PATTERN: - %5p}) %clr(${PID:- }){magenta} %clr([%thread]){yellow}  %cyan(%logger{39}:%L)  %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
    ru:
      ogbozoyan:
        cron:
          configuration:
            ControllerAdvice: OFF