version: '3.8'
services:
  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    entrypoint: [ "sh", "/usr/local/bin/check-and-pull.sh" ]
    volumes:
      - ./check-and-pull.sh:/usr/local/bin/check-and-pull.sh
